spring.application.name=api

spring.datasource.url=jdbc:mysql://localhost:3306/runab_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=runabSuperSecretKeyForCapstoneMustBeAtLeast32BytesLongForHS256
jwt.access-token-expiration-ms=86400000
jwt.temp-token-expiration-ms=600000



google.client-id=${GOOGLE_CLIENT_ID}

# ?? ?? (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nicksongmin102388@gmail.com
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8080